# Generated by Django 3.2.7 on 2023-09-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_banner_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('intercom', models.CharField(blank=True, max_length=255, null=True)),
                ('entrance', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='If bigger than 0, this price is higher in priority than the price for the delivery rule', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='If bigger than 0, this amount is higher in priority than the amount for the delivery rule', max_digits=10)),
                ('free_delivery_amount', models.DecimalField(decimal_places=2, default=0, help_text='If bigger than 0, this amount is higher in priority than the amount for the delivery rule', max_digits=10)),
                ('delivery_time', models.PositiveIntegerField(default=0, help_text='Estimated delivery time in minutes')),
                ('coordinates', models.TextField(help_text='Coordinates full array')),
                ('fill_color', models.CharField(blank=True, max_length=50, null=True)),
                ('outline_color', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institutions', models.ManyToManyField(to='company.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Pickup'), ('courier', 'Courier'), ('indoor', 'Indoor')], max_length=20)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, help_text='Price for a specific delivery type', max_digits=10)),
                ('free_delivery_amount', models.DecimalField(decimal_places=2, default=0, help_text='Delivery is free if total cart is bigger than this but if delivery_price is bigger than 0 (optional)', max_digits=10)),
                ('sale_type', models.CharField(blank=True, choices=[('absolute', 'Absolute'), ('percent', 'Percent')], help_text='Sale for a specific delivery type (optional)', max_length=20, null=True)),
                ('sale_amount', models.PositiveIntegerField(default=0)),
                ('min_order_amount', models.PositiveIntegerField(default=0, help_text='Minimum total cart price to use delivery (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('institutions', models.ManyToManyField(related_name='delivery', to='company.Institution')),
            ],
        ),
    ]
