# Generated by Django 3.2.7 on 2021-12-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Pickup'), ('takeaway', 'Takeaway'), ('institution', 'Institution')], max_length=20)),
                ('by_card', models.BooleanField(default=False)),
                ('by_cash', models.BooleanField(default=False)),
                ('by_card_online', models.BooleanField(default=False)),
                ('sale_type', models.CharField(choices=[('absolute', 'Absolute'), ('percent', 'Percent')], max_length=20)),
                ('sale_amount', models.IntegerField()),
                ('date_when', models.DateTimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='company.institution')),
            ],
        ),
    ]
