# Generated by Django 3.2.7 on 2022-03-14 09:38

import apps.delivery.services.upload_file
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_delivery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_time', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dz', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZoneСoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=255)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dz_coordinates', to='delivery.deliveryzone')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZoneFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.delivery.services.upload_file.get_path_upload_map_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['kml'])])),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dz_file_institution', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Pickup'), ('courier', 'Courier'), ('indoor', 'Indoor')], max_length=20)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')], default='online', max_length=20)),
                ('sale_type', models.CharField(choices=[('absolute', 'Absolute'), ('percent', 'Percent')], max_length=20)),
                ('sale_amount', models.IntegerField()),
                ('date_when', models.DateTimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='company.institution')),
            ],
        ),
    ]
