# Generated by Django 3.2.7 on 2022-05-19 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_design_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='date_when',
        ),
        migrations.AddField(
            model_name='delivery',
            name='cart_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='institution',
        ),
        migrations.AddField(
            model_name='delivery',
            name='institution',
            field=models.ManyToManyField(related_name='delivery', to='company.Institution'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='sale_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('absolute', 'Absolute'), ('percent', 'Percent')], max_length=20, null=True),
        ),
    ]
