# Generated by Django 3.2.7 on 2021-12-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='sale_amount',
            field=models.IntegerField(),
        ),
    ]
