# Generated by Django 3.2.7 on 2023-09-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('payment', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytyperule',
            name='payment_types',
            field=models.ManyToManyField(to='payment.PaymentTypeInstitution'),
        ),
        migrations.AddField(
            model_name='deliverytyperule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartdeliveryinfo',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
        migrations.AddField(
            model_name='cartdeliveryinfo',
            name='customer_address',
            field=models.ForeignKey(blank=True, help_text='address filled if delivery type is courier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.customeraddress'),
        ),
        migrations.AddField(
            model_name='cartdeliveryinfo',
            name='institution_address',
            field=models.ForeignKey(blank=True, help_text='address filled if delivery type is pickup or indoor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.institutionaddress'),
        ),
        migrations.AddField(
            model_name='cartdeliveryinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverytyperule'),
        ),
    ]
