# Generated by Django 3.2.7 on 2022-05-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20220519_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='cart_total',
            new_name='min_order_amount',
        ),
        migrations.AddField(
            model_name='delivery',
            name='free_delivery_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
