# Generated by Django 3.2.7 on 2021-12-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_sale_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='by_card',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='by_card_online',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='by_cash',
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')], default='online', max_length=20),
        ),
    ]
