# Generated by Django 3.2.7 on 2022-07-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20220726_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryZoneСoordinates',
            new_name='DeliveryZoneCoordinates',
        ),
    ]
