# Generated by Django 3.2.7 on 2022-05-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20220519_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='order_date',
        ),
    ]
