# Generated by Django 3.2.7 on 2023-10-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_yandexgeocodertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexgeocodertoken',
            name='api_key',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
