# Generated by Django 3.2.7 on 2021-12-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('delivery', '0003_auto_20211221_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_delivery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_time', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zone', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZoneСoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=255)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zone_coordinates', to='delivery.deliveryzone')),
            ],
        ),
    ]
