# Generated by Django 3.2.7 on 2023-11-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_yandexgeocodertoken_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='is_house',
            field=models.BooleanField(default=False),
        ),
    ]
