# Generated by Django 3.2.7 on 2021-12-31 13:52

import apps.delivery.services.upload_file
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('delivery', '0004_deliveryzone_deliveryzoneсoordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dz', to='company.institution'),
        ),
        migrations.AlterField(
            model_name='deliveryzoneсoordinates',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dz_coordinates', to='delivery.deliveryzone'),
        ),
        migrations.CreateModel(
            name='DeliveryZoneFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.delivery.services.upload_file.get_path_upload_map_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['kml'])])),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dz_file_institution', to='company.institution')),
            ],
        ),
    ]
