# Generated by Django 3.2.7 on 2022-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_delivery_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
