# Generated by Django 3.2.7 on 2022-01-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20211231_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('courier', 'Courier'), ('indoor', 'Indoor')], max_length=20),
        ),
    ]
