# Generated by Django 3.2.7 on 2023-11-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_customeraddress_is_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institutionaddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
