# Generated by Django 3.2.7 on 2022-06-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliveryinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='phone',
        ),
        migrations.AlterField(
            model_name='deliveryzoneсoordinates',
            name='coordinates',
            field=models.CharField(max_length=1000),
        ),
    ]
