# Generated by Django 3.2.7 on 2023-11-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20231125_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdeliveryinfo',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Delivery zone if exists and delivery type is courier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryzone'),
        ),
    ]
