# Generated by Django 3.2.7 on 2023-12-09 18:14

import apps.base.models.secure_charfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_cartdeliveryinfo_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexgeocodertoken',
            name='api_key',
            field=apps.base.models.secure_charfield.SecureCharField(max_length=512, unique=True),
        ),
    ]
