# Generated by Django 3.2.7 on 2022-06-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_addresslink_address'),
        ('delivery', '0007_auto_20220608_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.addresslink'),
        ),
    ]
