# Generated by Django 3.2.7 on 2023-12-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_yandexgeocodertoken_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytyperule',
            name='sale_amount',
        ),
        migrations.RemoveField(
            model_name='deliverytyperule',
            name='sale_type',
        ),
    ]
