# Generated by Django 3.2.7 on 2021-12-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.ManyToManyField(blank=True, to='media.Image')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additives', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('slug', models.SlugField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein', models.CharField(max_length=255)),
                ('fats', models.CharField(max_length=255)),
                ('carbohydrates', models.CharField(max_length=255)),
                ('calories', models.CharField(max_length=255)),
                ('weight_unit', models.CharField(choices=[('liter', 'Liter'), ('milliliter', 'Milliliter'), ('gram', 'Gram'), ('kilogram', 'Kilogram')], default='gram', max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('cook_time', models.IntegerField()),
                ('slug', models.SlugField()),
                ('additives', models.ManyToManyField(blank=True, to='product.Additive')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('images', models.ManyToManyField(blank=True, to='media.Image')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.institution')),
                ('modifiers', models.ManyToManyField(blank=True, to='product.Modifier')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.sticker')),
            ],
        ),
        migrations.CreateModel(
            name='ModifierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers_price', to='product.modifier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers_price', to='product.product')),
            ],
        ),
    ]
