# Generated by Django 3.2.7 on 2022-04-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_design_institution'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='institution',
        ),
        migrations.AddField(
            model_name='category',
            name='institution',
            field=models.ManyToManyField(related_name='categories', to='company.Institution'),
        ),
        migrations.RemoveField(
            model_name='categoryadditive',
            name='institution',
        ),
        migrations.AddField(
            model_name='categoryadditive',
            name='institution',
            field=models.ManyToManyField(related_name='category', to='company.Institution'),
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='institution',
        ),
        migrations.AddField(
            model_name='modifier',
            name='institution',
            field=models.ManyToManyField(related_name='modifiers', to='company.Institution'),
        ),
        migrations.RemoveField(
            model_name='modifierprice',
            name='institution',
        ),
        migrations.AddField(
            model_name='modifierprice',
            name='institution',
            field=models.ManyToManyField(related_name='modifiers_price', to='company.Institution'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='institution',
        ),
        migrations.AddField(
            model_name='product',
            name='institution',
            field=models.ManyToManyField(related_name='products', to='company.Institution'),
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='institution',
        ),
        migrations.AddField(
            model_name='sticker',
            name='institution',
            field=models.ManyToManyField(related_name='stickers', to='company.Institution'),
        ),
    ]
