# Generated by Django 3.2.7 on 2021-12-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cook_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, max_length=50),
        ),
    ]
