# Generated by Django 3.2.7 on 2023-05-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_workhours_user'),
        ('product', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additive',
            old_name='institution',
            new_name='institutions',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='institution',
            new_name='institutions',
        ),
        migrations.RenameField(
            model_name='modifier',
            old_name='institution',
            new_name='institutions',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='institution',
            new_name='institutions',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sticker',
            new_name='stickers',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='institution',
            new_name='institutions',
        ),
        migrations.RemoveField(
            model_name='categoryadditive',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='modifierprice',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='modifierprice',
            name='user',
        ),
        migrations.AddField(
            model_name='categoryadditive',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='category_additives', to='company.Institution'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category'),
        ),
        migrations.CreateModel(
            name='NutritionalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fats', models.FloatField(blank=True, null=True)),
                ('carbohydrates', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_values', to='product.modifier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_values', to='product.product')),
            ],
        ),
    ]
