# Generated by Django 3.2.7 on 2022-03-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_categoryadditive_additive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sticker',
        ),
        migrations.AddField(
            model_name='product',
            name='sticker',
            field=models.ManyToManyField(blank=True, to='product.Sticker'),
        ),
    ]
