# Generated by Django 3.2.7 on 2022-04-27 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_design_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='institution',
            field=models.ManyToManyField(blank=True, related_name='categories', to='company.Institution'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser'),
        ),
    ]
