# Generated by Django 3.2.7 on 2021-12-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211221_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='row',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='order',
            new_name='row',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.sticker'),
        ),
    ]
