# Generated by Django 3.2.7 on 2022-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220314_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additives',
            field=models.ManyToManyField(blank=True, related_name='product_additives', to='product.CategoryAdditive'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='product_modifiers', to='product.Modifier'),
        ),
    ]
