# Generated by Django 3.2.7 on 2021-12-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211221_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='text_color',
            field=models.CharField(default='#000', max_length=20),
        ),
    ]
