# Generated by Django 3.2.7 on 2022-04-27 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_alter_design_institution'),
        ('product', '0004_auto_20220427_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='additive',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryadditive',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modifier',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modifierprice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sticker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='additive',
            name='institution',
        ),
        migrations.AddField(
            model_name='additive',
            name='institution',
            field=models.ManyToManyField(blank=True, related_name='additives', to='company.Institution'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoryadditive',
            name='institution',
            field=models.ManyToManyField(blank=True, related_name='category', to='company.Institution'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='institution',
            field=models.ManyToManyField(blank=True, related_name='modifiers', to='company.Institution'),
        ),
        migrations.AlterField(
            model_name='modifierprice',
            name='institution',
            field=models.ManyToManyField(blank=True, related_name='modifiers_price', to='company.Institution'),
        ),
        migrations.AlterField(
            model_name='product',
            name='institution',
            field=models.ManyToManyField(blank=True, related_name='products', to='company.Institution'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='institution',
            field=models.ManyToManyField(blank=True, related_name='stickers', to='company.Institution'),
        ),
    ]
