# Generated by Django 3.2.7 on 2023-05-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20230528_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_unit', models.CharField(choices=[('liter', 'Liter'), ('milliliter', 'Milliliter'), ('gram', 'Gram'), ('kilogram', 'Kilogram')], default='gram', max_length=50)),
                ('weight', models.FloatField(max_length=50)),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='product.modifier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='product.product')),
            ],
        ),
    ]
