# Generated by Django 3.2.7 on 2022-04-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('product', '0004_auto_20220319_1544'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modifierprice',
            unique_together={('institution', 'product', 'modifier')},
        ),
    ]
