# Generated by Django 3.2.7 on 2021-12-22 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('product', '0005_sticker_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifierprice',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifiers_price', to='company.institution'),
        ),
    ]
