# Generated by Django 3.2.7 on 2023-07-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additive',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additive_category', to='product.categoryadditive'),
        ),
    ]
