# Generated by Django 3.2.7 on 2022-01-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_institution_qrcode'),
        ('product', '0007_auto_20211222_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='additive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='additive',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CategoryAdditive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('row', models.PositiveIntegerField(default=1)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='company.institution')),
            ],
        ),
        migrations.AddField(
            model_name='additive',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_additive', to='product.categoryadditive'),
        ),
    ]
