# Generated by Django 3.2.7 on 2022-01-27 11:54

import apps.product.services.path_additive_img
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220112_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additive',
            name='images',
        ),
        migrations.AddField(
            model_name='additive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.product.services.path_additive_img.get_path_additive, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
