version: '3'

services:
  backend:
    build: .
    container_name: efood_backend
    #hostname: efood_backend
    #restart: always
    command: bash entrypoint.sh
    # volumes соответствие директорий на локальной машине и в контейнрер
    volumes:
      - .:/efood
      - ./static:/efood/static
      - ./media:/efood/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgdb
      - celery
      - redis
    links:
      - pgdb:pgdb
#    networks:
#      - djangonetwork

  celery:
    build: .
    container_name: efood_celery
    command: celery -A project worker -l INFO
    volumes:
      - .:/efood
    env_file:
      - .env
    depends_on:
      - redis
      - pgdb

  celery_beat:
    build: .
    container_name: efood_celery_beat
    command: celery -A project beat -l info
    env_file:
      - .env
    depends_on:
      - redis
      - pgdb
      - celery
    volumes:
      - .:/efood

  pgdb:
    image: postgres
    container_name: efood_pgdb
    env_file:
      - .env
    volumes:
      - efood-pgdata:/var/lib/postgresql/data/
#    networks:
#      - djangonetwork

  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=8888' ]
    ports:
      - 8888:8888
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: efood_redis

  nginx:
    build: ./nginx
    container_name: efood_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - backend

volumes:
  efood-pgdata:
#networks:
#      djangonetwork:
#        driver: bridge
