# Generated by Django 3.2.7 on 2023-04-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_promo',
            new_name='is_free_promo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='is_sms_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
