# Generated by Django 3.2.7 on 2022-04-13 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220411_2024'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='Unique phone numbers for users',
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='Unique emails for users',
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='Unique usernames for users',
        ),
        migrations.AlterField(
            model_name='authcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
