# Generated by Django 3.2.7 on 2022-04-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220413_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'В очереди'), (1, 'Доставлено'), (2, 'Не доставлено'), (3, 'Передано'), (4, 'Ожидание статуса сообщения'), (6, 'Отклонено'), (8, 'На модерации')], default=None, null=True, verbose_name='Статус'),
        ),
    ]
