# Generated by Django 3.2.7 on 2022-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220225_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
