# Generated by Django 3.2.7 on 2023-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='status',
            field=models.CharField(choices=[(0, 'success'), (1, 'error')], default=None, max_length=3),
        ),
    ]
