# Generated by Django 3.2.7 on 2023-05-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_messagelog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='sender',
        ),
        migrations.DeleteModel(
            name='AuthCode',
        ),
        migrations.DeleteModel(
            name='Sms',
        ),
    ]
