# Generated by Django 3.2.7 on 2023-05-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230520_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='type',
            field=models.CharField(choices=[(0, 'Email verification'), (1, 'Email confirmation'), (3, 'Phone verification'), (4, 'Phone confirmation'), (5, 'Registration organization'), (6, 'Login organization'), (7, 'Registration customer'), (8, 'Login customer')], max_length=3),
        ),
    ]
