# Generated by Django 3.2.7 on 2021-12-12 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('keywords', models.CharField(blank=True, max_length=250, verbose_name='Keywords')),
                ('h1', models.CharField(blank=True, max_length=250, verbose_name='H1')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, upload_to='images/users/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('phone', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('local_time', models.CharField(max_length=255)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField()),
                ('vkontakte', models.URLField()),
                ('facebook', models.URLField()),
                ('youtube', models.URLField()),
                ('tiktok', models.URLField()),
                ('tripadvisor', models.URLField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inn', models.IntegerField()),
                ('kpp', models.IntegerField()),
                ('ogrn', models.IntegerField()),
                ('bank', models.CharField(max_length=255)),
                ('bik', models.IntegerField()),
                ('correspondent_account', models.IntegerField()),
                ('checking_account', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.address')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/users/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('link', models.URLField()),
                ('link_text', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_metrics', models.TextField()),
                ('google_analytics', models.TextField()),
                ('google_tags', models.TextField()),
                ('facebook_pixel', models.TextField()),
                ('vk_pixel', models.TextField()),
                ('tiktok_pixel', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='company.institution')),
            ],
        ),
    ]
