# Generated by Django 3.2.7 on 2022-04-10 13:27

import apps.company.services.path_banner
import apps.company.services.path_qr_code
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_metrics', models.CharField(blank=True, max_length=100)),
                ('google_analytics', models.CharField(blank=True, max_length=100)),
                ('google_tags', models.CharField(blank=True, max_length=100)),
                ('facebook_pixel', models.CharField(blank=True, max_length=100)),
                ('vk_pixel', models.CharField(blank=True, max_length=100)),
                ('tiktok_pixel', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('position', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=250, verbose_name='Keywords')),
                ('seo_h1', models.CharField(blank=True, max_length=250, verbose_name='H1')),
                ('city', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('building', models.CharField(blank=True, max_length=255)),
                ('office', models.CharField(blank=True, max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('local_time', models.CharField(choices=[('moscow', 'UTC+3'), ('kaliningrad', 'UTC+2'), ('samara', 'UTC+4'), ('yekaterinburg', 'UTC+5'), ('omsk', 'UTC+6'), ('krasnoyarsk', 'UTC+7'), ('novosibirsk', 'UTC+7'), ('irkutsk', 'UTC+8'), ('Yakutsk', 'UTC+9'), ('vladivostok', 'UTC+10'), ('Magadan', 'UTC+11'), ('Sakhalin', 'UTC+11'), ('Srednekolymsk', 'UTC+11'), ('Anadyr', 'UTC+12'), ('Kamchatka', 'UTC+12')], default='moscow', max_length=20)),
                ('qrcode', models.ImageField(blank=True, upload_to=apps.company.services.path_qr_code.get_path_qr_code)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.address')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.image')),
                ('other_phone', models.ManyToManyField(blank=True, related_name='institutions', to='company.ExtraPhone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('vkontakte', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('youtube', models.CharField(blank=True, max_length=100)),
                ('tiktok', models.CharField(blank=True, max_length=100)),
                ('tripadvisor', models.CharField(blank=True, max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inn', models.IntegerField()),
                ('kpp', models.IntegerField()),
                ('ogrn', models.IntegerField()),
                ('bank', models.CharField(max_length=255)),
                ('bik', models.IntegerField()),
                ('correspondent_account', models.IntegerField()),
                ('checking_account', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.address')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='MinCartCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_cart_value', to='company.institution')),
            ],
        ),
        migrations.AddField(
            model_name='extraphone',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_phone', to='company.institution'),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='company.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.company.services.path_banner.get_path_banner, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('row', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='company.institution')),
            ],
        ),
    ]
