# Generated by Django 3.2.7 on 2023-09-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='banner', to='product.Product'),
        ),
    ]
