# Generated by Django 3.2.7 on 2022-06-29 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('company', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.address'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='company.institution'),
        ),
        migrations.AddField(
            model_name='mincartcost',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_cart_value', to='company.institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='other_phone',
            field=models.ManyToManyField(blank=True, related_name='inst_other_phone', to='company.ExtraPhone'),
        ),
        migrations.AddField(
            model_name='institution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inst_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extraphone',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_phone', to='company.institution'),
        ),
        migrations.AddField(
            model_name='design',
            name='institution',
            field=models.ManyToManyField(related_name='design', to='company.Institution'),
        ),
        migrations.AddField(
            model_name='design',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banner',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='company.institution'),
        ),
        migrations.AddField(
            model_name='banner',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='banner', to='product.Product'),
        ),
        migrations.AddField(
            model_name='banner',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner', to='order.promocode'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='company.institution'),
        ),
    ]
