# Generated by Django 3.2.7 on 2021-12-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('company', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='banner', to='product.Product'),
        ),
        migrations.AddField(
            model_name='banner',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner', to='order.promocode'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='company.institution'),
        ),
    ]
