# Generated by Django 3.2.7 on 2021-12-17 10:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='h1',
            new_name='seo_h1',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='keywords',
            new_name='seo_keywords',
        ),
        migrations.AddField(
            model_name='institution',
            name='seo_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='institution',
            name='seo_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
