# Generated by Django 3.2.7 on 2023-05-20 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='institution',
            new_name='institutions',
        ),
        migrations.RenameField(
            model_name='extraphone',
            old_name='institution',
            new_name='institutions',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='institution',
            new_name='institutions',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='mincartcost',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='institution',
        ),
        migrations.AddField(
            model_name='banner',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='banner', to='company.Institution'),
        ),
        migrations.AddField(
            model_name='banner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extraphone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extraphone',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mincartcost',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='min_cart_cost', to='company.Institution'),
        ),
        migrations.AddField(
            model_name='mincartcost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisites',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='requisites', to='company.Institution'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extraphone',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mincartcost',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
