# Generated by Django 3.2.7 on 2022-01-04 18:24

import apps.company.services.path_qr_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to=apps.company.services.path_qr_code.get_path_qr_code),
        ),
    ]
