# Generated by Django 3.2.7 on 2022-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='institution',
        ),
        migrations.AddField(
            model_name='design',
            name='institution',
            field=models.ManyToManyField(null=True, related_name='design', to='company.Institution'),
        ),
    ]
