# Generated by Django 3.2.7 on 2021-12-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20211217_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='local_time',
            field=models.CharField(choices=[('moscow', 'UTC+3'), ('kaliningrad', 'UTC+2'), ('samara', 'UTC+4'), ('yekaterinburg', 'UTC+5'), ('omsk', 'UTC+6'), ('krasnoyarsk', 'UTC+7'), ('novosibirsk', 'UTC+7'), ('irkutsk', 'UTC+8'), ('Yakutsk', 'UTC+9'), ('vladivostok', 'UTC+10'), ('Magadan', 'UTC+11'), ('Sakhalin', 'UTC+11'), ('Srednekolymsk', 'UTC+11'), ('Anadyr', 'UTC+12'), ('Kamchatka', 'UTC+12')], max_length=20),
        ),
    ]
