# Generated by Django 3.2.7 on 2023-05-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20230520_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraphone',
            name='institutions',
        ),
        migrations.AddField(
            model_name='extraphone',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='extra_phone', to='company.Institution'),
        ),
    ]
