# Generated by Django 3.2.7 on 2021-12-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_institution_local_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='building',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='office',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
