# Generated by Django 3.2.7 on 2022-05-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_design_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='building',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='office',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='region',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='street',
        ),
    ]
