# Generated by Django 3.2.7 on 2022-04-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220426_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='institution',
            field=models.ManyToManyField(related_name='design', to='company.Institution'),
        ),
    ]
