# Generated by Django 3.2.7 on 2021-12-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20211218_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='logo',
        ),
    ]
