# Generated by Django 3.2.7 on 2022-01-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_banner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='row',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
