# Generated by Django 3.2.7 on 2022-04-30 12:49

import apps.company.services.path_logo
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_alter_design_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='address',
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.company.services.path_logo.get_path_logo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='other_phone',
            field=models.ManyToManyField(blank=True, related_name='inst_other_phone', to='company.ExtraPhone'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inst_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
