# Generated by Django 3.2.7 on 2021-12-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('company', '0005_remove_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.image'),
        ),
    ]
