# Generated by Django 3.2.7 on 2023-05-28 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_weekday'),
        ('company', '0005_auto_20230528_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Work hours for 'Pizza Uno' at weekend.", max_length=255)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('institutions', models.ManyToManyField(related_name='work_hours', to='company.Institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weekdays', models.ManyToManyField(to='base.WeekDay')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
    ]
