# Generated by Django 3.2.7 on 2022-01-14 09:34

import apps.company.services.path_banner
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_banner_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to=apps.company.services.path_banner.get_path_banner),
        ),
    ]
