# Generated by Django 3.2.7 on 2021-12-19 14:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='local_time',
            field=models.CharField(choices=[('moscow', 'UTC+3'), ('kaliningrad', 'UTC+2'), ('samara', 'UTC+4'), ('yekaterinburg', 'UTC+5'), ('omsk', 'UTC+6'), ('krasnoyarsk', 'UTC+7'), ('novosibirsk', 'UTC+7'), ('irkutsk', 'UTC+8'), ('Yakutsk', 'UTC+9'), ('vladivostok', 'UTC+10'), ('Magadan', 'UTC+11'), ('Sakhalin', 'UTC+11'), ('Srednekolymsk', 'UTC+11'), ('Anadyr', 'UTC+12'), ('Kamchatka', 'UTC+12')], default='moscow', max_length=20),
        ),
        migrations.CreateModel(
            name='ExtraPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_phone', to='company.institution')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='other_phone',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='company.ExtraPhone'),
        ),
    ]
