# Generated by Django 3.2.7 on 2022-01-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraphone',
            old_name='position',
            new_name='row',
        ),
    ]
