# Generated by Django 3.2.7 on 2023-07-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_workhours_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraphone',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
