# Generated by Django 3.2.7 on 2022-01-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_rename_position_extraphone_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraphone',
            old_name='row',
            new_name='position',
        ),
    ]
