# Generated by Django 3.2.7 on 2021-12-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20211219_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='facebook_pixel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='google_analytics',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='google_tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='tiktok_pixel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='vk_pixel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='yandex_metrics',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
