# Generated by Django 3.2.7 on 2021-12-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20211219_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='tripadvisor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='vkontakte',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='youtube',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
