# Generated by Django 3.2.7 on 2022-01-26 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_row_extraphone_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinCartCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_cart_value', to='company.institution')),
            ],
        ),
    ]
