# Generated by Django 3.2.7 on 2021-12-19 18:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20211219_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
