# Generated by Django 3.2.7 on 2021-12-19 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0002_auto_20211212_1442'),
        ('company', '0011_alter_requisites_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='banner', to='product.Product'),
        ),
        migrations.AddField(
            model_name='banner',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner', to='order.promocode'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
