# Generated by Django 3.2.7 on 2022-01-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_institution_qrcode'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('write_off', models.PositiveIntegerField()),
                ('accrual', models.PositiveIntegerField()),
                ('is_registration_bonus', models.BooleanField(default=False)),
                ('registration_bonus', models.PositiveIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='company.institution')),
            ],
        ),
    ]
