# Generated by Django 3.2.7 on 2023-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='delivery_free',
            field=models.BooleanField(default=False),
        ),
    ]
