# Generated by Django 3.2.7 on 2021-12-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.promocode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='cart_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code_use',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code_use_by_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='date_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='delivery_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
