# Generated by Django 3.2.7 on 2023-12-03 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20231201_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='accrual',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='write_off',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
