# Generated by Django 3.2.7 on 2022-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220511_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
