# Generated by Django 3.2.7 on 2023-02-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0002_auto_20230104_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additives',
            field=models.ManyToManyField(blank=True, to='product.Additive'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.modifierprice'),
        ),
    ]
