# Generated by Django 3.2.7 on 2022-01-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='is_promo_code',
            field=models.BooleanField(default=False),
        ),
    ]
