# Generated by Django 3.2.7 on 2023-12-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20231203_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='delivery_free',
            new_name='is_delivery_free',
        ),
    ]
