# Generated by Django 3.2.7 on 2023-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20230219_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
