# Generated by Django 3.2.7 on 2022-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='num_uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
