# Generated by Django 3.2.7 on 2022-04-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='total_coast',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
