# Generated by Django 3.2.7 on 2022-05-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
