# Generated by Django 3.2.7 on 2022-05-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_key',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.JSONField(default=dict),
        ),
    ]
