# Generated by Django 3.2.7 on 2022-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_promocode_num_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('on the way', 'On the way'), ('delivered', 'Delivered'), ('given away', 'Given away')], default='placed', max_length=10),
        ),
    ]
