# Generated by Django 3.2.7 on 2023-12-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_delivery_free_promocode_is_delivery_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='min_amount',
        ),
    ]
