# Generated by Django 3.2.7 on 2022-06-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_deliveryinfo_address'),
        ('order', '0005_auto_20220516_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_delivery', to='delivery.deliveryinfo'),
        ),
    ]
