# Generated by Django 3.2.7 on 2022-08-21 15:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220821_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='имя', max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
