# Generated by Django 3.2.7 on 2022-04-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220319_1544'),
        ('order', '0005_auto_20220403_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='additives',
            field=models.ManyToManyField(blank=True, related_name='cart_products', to='product.Additive'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='cart_products', to='product.Modifier'),
        ),
    ]
