# Generated by Django 3.2.7 on 2023-04-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20230319_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('accepted', 'Accepted'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('on the way', 'On the way'), ('delivered', 'Delivered'), ('given away', 'Given away'), ('cancel', 'Cancel')], default='draft', max_length=10),
        ),
    ]
