# Generated by Django 3.2.7 on 2022-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220821_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('accepted', 'Accepted'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('on the way', 'On the way'), ('delivered', 'Delivered'), ('given away', 'Given away')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('accepted', 'Accepted'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('on the way', 'On the way'), ('delivered', 'Delivered'), ('given away', 'Given away')], default='placed', max_length=10),
        ),
    ]
