# Generated by Django 3.2.7 on 2022-04-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220403_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_coast',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
