# Generated by Django 3.2.7 on 2023-04-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
