# Generated by Django 3.2.7 on 2022-01-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_row_extraphone_position'),
        ('order', '0007_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_bonus', to='order.bonus'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_institution', to='company.institution'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_promo_code', to='order.promocode'),
        ),
    ]
