# Generated by Django 3.2.7 on 2022-04-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_cart_total_coast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_coast',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
