# Generated by Django 3.2.7 on 2022-09-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220821_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbonus',
            name='bonus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
