# Generated by Django 3.2.7 on 2023-07-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_workhours_user'),
        ('order', '0008_remove_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='institution',
        ),
        migrations.AddField(
            model_name='promocode',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='promocode', to='company.Institution'),
        ),
    ]
