# Generated by Django 3.2.7 on 2022-06-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('courier', 'Courier'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('on the way', 'On the way'), ('delivered', 'Delivered'), ('given away', 'Given away')], default='pickup', max_length=10),
        ),
    ]
