# Generated by Django 3.2.7 on 2023-07-11 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_alter_workhours_user'),
        ('order', '0010_promocode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='institution',
        ),
        migrations.AddField(
            model_name='bonus',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='bonuses', to='company.Institution'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
