# Generated by Django 3.2.7 on 2022-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('on the way', 'On the way'), ('delivered', 'Delivered'), ('given away', 'Given away')], default='placed', max_length=10),
        ),
    ]
