# Generated by Django 3.2.7 on 2023-07-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20230711_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
