# Generated by Django 3.2.7 on 2022-01-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20220121_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='num_uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
