# Generated by Django 3.2.7 on 2022-01-25 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0012_promocode_num_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='cart_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code_use',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code_use_by_user',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='num_uses',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='sale',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='PromoCodeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_uses', models.PositiveIntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='order.promocode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('code', 'user')},
            },
        ),
    ]
