# Generated by Django 3.2.7 on 2023-08-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_cartitem_item_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='min_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
