# Generated by Django 3.2.7 on 2022-01-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20220125_1029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocodeuser',
            unique_together=set(),
        ),
    ]
