# Generated by Django 3.2.7 on 2023-08-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20230803_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code_use',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code_use_by_user',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
