# Generated by Django 3.2.7 on 2023-08-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20230803_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='cart_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
