# Generated by Django 3.2.7 on 2022-01-25 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_row_extraphone_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0014_alter_promocodeuser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodeuser',
            name='num_uses',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='UserBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.PositiveIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonuses', to='company.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
