# Generated by Django 3.2.7 on 2022-01-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_userbonus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='registration_bonus',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
