# Generated by Django 3.2.7 on 2022-01-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_mincartcost'),
        ('order', '0017_alter_bonus_registration_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='min_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_cart_amount', to='company.mincartcost'),
        ),
    ]
