# Generated by Django 3.2.7 on 2022-01-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_cart_min_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_bonus',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
