# Generated by Django 3.2.7 on 2022-02-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_cart_customer_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
