# Generated by Django 3.2.7 on 2022-02-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_cart_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
    ]
