# Generated by Django 3.2.7 on 2023-01-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
