# Generated by Django 3.2.7 on 2023-09-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'В очереди'), (1, 'Доставлено'), (2, 'Не доставлено'), (3, 'Передано'), (4, 'Ожидание статуса сообщения'), (6, 'Отклонено'), (8, 'На модерации')], default=None, null=True, verbose_name='Статус')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sms Log',
                'verbose_name_plural': 'Sms Logs',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSmsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sms provider title')),
                ('api_login', models.CharField(max_length=500, verbose_name='API login, account id or any auth data')),
                ('api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='API key, token or password')),
                ('api_additional', models.CharField(blank=True, max_length=500, null=True, verbose_name='Any API additional data if needed')),
                ('company_title', models.CharField(blank=True, help_text='Show company title as a message sender.', max_length=255, null=True, verbose_name='Company title')),
                ('from_phone', models.CharField(blank=True, help_text='If company title is not possible to use.', max_length=100, null=True, verbose_name='Sending message from that phone number')),
                ('is_active', models.BooleanField(default=True)),
                ('institutions', models.ManyToManyField(to='company.Institution', verbose_name='Could choose only specific affiliates or all')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User as organization')),
            ],
        ),
    ]
