# Generated by Django 3.2.7 on 2023-04-29 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'В очереди'), (1, 'Доставлено'), (2, 'Не доставлено'), (3, 'Передано'), (4, 'Ожидание статуса сообщения'), (6, 'Отклонено'), (8, 'На модерации')], default=None, null=True, verbose_name='Статус')),
                ('status_text', models.TextField(blank=True, default=None, null=True, verbose_name='Статус-сообщение')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sms Log',
                'verbose_name_plural': 'Sms Logs',
            },
        ),
    ]
