# Generated by Django 3.2.7 on 2023-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='status_text',
        ),
        migrations.AlterField(
            model_name='smslog',
            name='sms_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
