# Generated by Django 3.2.7 on 2023-04-30 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_initial'),
        ('sms', '0002_auto_20230429_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSmsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sms provider title')),
                ('api_login', models.CharField(max_length=500, verbose_name='API login, account id or any auth data')),
                ('api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='API key, token or password')),
                ('api_additional', models.CharField(blank=True, max_length=500, null=True, verbose_name='Any API additional data if needed')),
                ('is_active', models.BooleanField(default=True)),
                ('institutions', models.ManyToManyField(to='company.Institution', verbose_name='Could choose only specific affiliates or all')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User as organization')),
            ],
        ),
    ]
