# Generated by Django 3.2.7 on 2023-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_organizationsmsprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsmsprovider',
            name='company_title',
            field=models.CharField(blank=True, help_text='Show company title as a message sender.', max_length=255, null=True, verbose_name='Company title'),
        ),
        migrations.AddField(
            model_name='organizationsmsprovider',
            name='from_phone',
            field=models.CharField(blank=True, help_text='If company title is not possible to use.', max_length=100, null=True, verbose_name='Sending message from that phone number'),
        ),
    ]
