# Generated by Django 3.2.7 on 2022-05-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='office',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
