# Generated by Django 3.2.7 on 2022-05-27 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_auto_20220527_1051'),
        ('location', '0003_auto_20220521_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
        migrations.AddField(
            model_name='address',
            name='display_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.address'),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.institution'),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
