# Generated by Django 3.2.7 on 2022-06-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20220527_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresslink',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
