# Generated by Django 3.2.7 on 2022-06-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_addresslink_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresslink',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='location.address'),
        ),
    ]
