# Generated by Django 3.2.7 on 2023-01-03 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Que',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('accepted', 'Accepted'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('canceled', 'Canceled')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='que', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='que', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
