# Generated by Django 3.2.7 on 2023-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='que',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
