# Generated by Django 3.2.7 on 2023-04-02 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0002_que_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='que',
            name='number',
        ),
        migrations.AddField(
            model_name='que',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
