# Generated by Django 3.2.7 on 2023-04-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0003_auto_20230402_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='que',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('accepted', 'Accepted'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('canceled', 'Canceled')], default='processing', max_length=20),
        ),
    ]
