# Generated by Django 3.2.7 on 2023-04-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0004_alter_que_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='que',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
