# Generated by Django 3.2.7 on 2022-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_institutions', models.PositiveIntegerField(default=0)),
                ('max_banners', models.PositiveIntegerField(default=0)),
                ('is_delivery_zone', models.BooleanField(default=False)),
                ('is_live_queue', models.BooleanField(default=False)),
                ('is_design', models.BooleanField(default=False)),
                ('is_notifications', models.BooleanField(default=False)),
                ('is_integrations', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('max_analytics', models.ManyToManyField(to='company.Analytics')),
            ],
        ),
    ]
