# Generated by Django 3.2.7 on 2024-02-24 12:44

import apps.base.models.secure_charfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeintegration',
            name='api_key',
            field=apps.base.models.secure_charfield.SecureCharField(max_length=512, unique=True),
        ),
    ]
