# Generated by Django 3.2.7 on 2024-03-02 16:21

import apps.base.models.secure_charfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_stripeintegration_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yoomoney',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='yoomoney',
            name='is_test',
        ),
        migrations.RemoveField(
            model_name='yoomoney',
            name='oauth_key',
        ),
        migrations.AlterField(
            model_name='yoomoney',
            name='wallet',
            field=apps.base.models.secure_charfield.SecureCharField(max_length=512, unique=True),
        ),
    ]
