# Generated by Django 3.2.7 on 2023-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_stripeintegration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, help_text='The payment id provided by the payment gateway', max_length=255, null=True),
        ),
    ]
