# Generated by Django 3.2.7 on 2022-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20220527_1051'),
        ('payment', '0002_paymenttypeinstitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttypeinstitution',
            name='institution',
            field=models.ManyToManyField(related_name='payment_type', to='company.Institution'),
        ),
    ]
