# Generated by Django 3.2.7 on 2022-06-23 20:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_auto_20220527_1051'),
        ('payment', '0005_alter_yoomoney_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='system',
        ),
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 23, 20, 27, 3, 709126, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_inst', to='company.institution'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('pending', 'Pending'), ('declined', 'Declined'), ('rejected', 'Rejected'), ('success', 'Success')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='order.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
