# Generated by Django 3.2.7 on 2022-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20220623_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoomoney',
            name='client_id',
            field=models.CharField(default='xxx', max_length=1000),
        ),
        migrations.AddField(
            model_name='yoomoney',
            name='oauth_key',
            field=models.CharField(default='xxx', max_length=1000),
        ),
    ]
