# Generated by Django 3.2.7 on 2022-06-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20220624_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoomoney',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='yoomoney',
            name='client_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='yoomoney',
            name='oauth_key',
            field=models.CharField(max_length=1000),
        ),
    ]
